// <auto-generated />
using System;
using ComponentHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComponentHotel.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentHotelCL.Gast", b =>
                {
                    b.Property<int>("GastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastId"));

                    b.Property<string>("Achternaam")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Huisnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .IsUnicode(false)
                        .HasColumnType("varchar(34)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Straat");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Telefoonnummer");

                    b.Property<string>("Voornaam")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GastId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Gast_Email");

                    b.ToTable("Gasten", (string)null);

                    b.HasData(
                        new
                        {
                            GastId = 1,
                            Achternaam = "Jansen",
                            Email = "jan@example.com",
                            Huisnummer = "1A",
                            IBAN = "NL91ABNA0417164300",
                            Land = "Netherlands",
                            Postcode = "1234AB",
                            Straat = "Hoofdstraat",
                            Telefoonnummer = "0612345678",
                            Voornaam = "Jan",
                            Woonplaats = "Amsterdam"
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("GastId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WachtwoordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("GebruikerId");

                    b.HasIndex("GastId");

                    b.ToTable("Gebruikers", (string)null);

                    b.HasData(
                        new
                        {
                            GebruikerId = 1,
                            Email = "admin@example.com",
                            GastId = 1,
                            Rol = "Admin",
                            WachtwoordHash = "REPLACE_WITH_HASH"
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.Hotelkamer", b =>
                {
                    b.Property<int>("HotelkamerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelkamerId"));

                    b.Property<bool>("IsBeschikbaar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kamernummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PrijsPerNacht")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HotelkamerId");

                    b.ToTable("Hotelkamers", (string)null);

                    b.HasData(
                        new
                        {
                            HotelkamerId = 1,
                            IsBeschikbaar = true,
                            Kamernummer = "101",
                            PrijsPerNacht = 75.00m,
                            Type = "Standaard"
                        },
                        new
                        {
                            HotelkamerId = 2,
                            IsBeschikbaar = true,
                            Kamernummer = "102",
                            PrijsPerNacht = 95.50m,
                            Type = "Comfort"
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.Reservering", b =>
                {
                    b.Property<int>("ReserveringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReserveringId"));

                    b.Property<int>("GastId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncheckDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TariefId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UitcheckDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("ReserveringId");

                    b.HasIndex("GastId");

                    b.HasIndex("TariefId");

                    b.ToTable("Reserveringen", (string)null);

                    b.HasData(
                        new
                        {
                            ReserveringId = 1,
                            GastId = 1,
                            IncheckDatum = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            TariefId = 1,
                            UitcheckDatum = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.ReserveringHotelkamer", b =>
                {
                    b.Property<int>("ReserveringId")
                        .HasColumnType("int");

                    b.Property<int>("HotelkamerId")
                        .HasColumnType("int");

                    b.HasKey("ReserveringId", "HotelkamerId");

                    b.HasIndex("HotelkamerId");

                    b.ToTable("ReserveringHotelkamers", (string)null);

                    b.HasData(
                        new
                        {
                            ReserveringId = 1,
                            HotelkamerId = 1
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.Tarief", b =>
                {
                    b.Property<int>("TariefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariefId"));

                    b.Property<decimal>("BedragNaKorting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BerekendOp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KortingPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ReserveringId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotaal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToeristenbelastingPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotaalBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TariefId");

                    b.HasIndex("ReserveringId");

                    b.ToTable("Tarieven", (string)null);

                    b.HasData(
                        new
                        {
                            TariefId = 1,
                            BedragNaKorting = 270.00m,
                            BerekendOp = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KortingPercentage = 10.00m,
                            ReserveringId = 1,
                            Subtotaal = 300.00m,
                            ToeristenbelastingPercentage = 5.00m,
                            TotaalBedrag = 283.50m
                        });
                });

            modelBuilder.Entity("ComponentHotelCL.Gebruiker", b =>
                {
                    b.HasOne("ComponentHotelCL.Gast", "Gast")
                        .WithMany()
                        .HasForeignKey("GastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gast");
                });

            modelBuilder.Entity("ComponentHotelCL.Reservering", b =>
                {
                    b.HasOne("ComponentHotelCL.Gast", "Gast")
                        .WithMany()
                        .HasForeignKey("GastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComponentHotelCL.Tarief", "Tarief")
                        .WithMany()
                        .HasForeignKey("TariefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gast");

                    b.Navigation("Tarief");
                });

            modelBuilder.Entity("ComponentHotelCL.ReserveringHotelkamer", b =>
                {
                    b.HasOne("ComponentHotelCL.Hotelkamer", "Hotelkamer")
                        .WithMany("ReserveringHotelkamers")
                        .HasForeignKey("HotelkamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComponentHotelCL.Reservering", "Reservering")
                        .WithMany("ReserveringHotelkamers")
                        .HasForeignKey("ReserveringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotelkamer");

                    b.Navigation("Reservering");
                });

            modelBuilder.Entity("ComponentHotelCL.Tarief", b =>
                {
                    b.HasOne("ComponentHotelCL.Reservering", "Reservering")
                        .WithMany()
                        .HasForeignKey("ReserveringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservering");
                });

            modelBuilder.Entity("ComponentHotelCL.Hotelkamer", b =>
                {
                    b.Navigation("ReserveringHotelkamers");
                });

            modelBuilder.Entity("ComponentHotelCL.Reservering", b =>
                {
                    b.Navigation("ReserveringHotelkamers");
                });
#pragma warning restore 612, 618
        }
    }
}
